### ISSUE TITLE
Faulty/ large  ODD freezes the application

### ISSUE THREAD

**Issue by lb42** [TEIC/romajs#158] opened 2023-07-30 11:25 UTC
The current roma does not recover gracefully when asked to load a faulty ODD file. An invalid or ill formed XML document should generate a message saying the file is no good, not simply freeze the application. A little more problematic but equally annoying: a file containing an incomplete schemaSpec (such as teiPublisher persistently calls an ODD) should also generate a warning/error message.

**Comment by lb42** [comment] 2023-08-01 11:08
In testing this, I have noticed that even valid ODD files can cause the app to freeze when importing an ODD. I am not sure what causes this, but size seems to be a factor. For example the dracor odd (https://github.com/dracor-org/dracor-schema/tree/main/odd) tho perfectly acceptable to e.g. oxYgen or the TEI odd2relaxng command won't even display the "2/3 importing customisation" message, but just sits there like a pudding

**Comment by lb42** [comment] 2023-08-01 12:22
The Epidoc ODD (https://github.com/EpiDoc/Source/blob/main/schema/tei-epidoc.xml) also freezes the app. This suggests the current code is just unable to handle large ODDs. Note that roma-antiqua has no problem loading either this or the dracor schema. So I think this is a BUG not an enhancement!

**Comment by lb42** [comment] 2023-08-01 13:47
Firefox on ubuntu. But i have the same issue with chromium on ubuntu

**Comment by raffazizzi** [comment] 2023-08-01 15:06
Thanks, @lb42. I can confirm that the error handling was not working as expected and I just pushed a fix (which won't appear on roma.tei-c.org until next release).

For Dracor and Epidoc, the problem isn't the size, but the fact that they use `@source` (presumably to chain ODDs). Roma doesn't support this yet. With the new fix, the user is presented with the correct error report:

![image](https://github.com/TEIC/romajs/assets/144770/f1f4b63b-87da-437e-89c9-1ebe00969a61)

**Closed by raffazizzi** 2023-08-01 15:06 UTC
Labels: bug
