### ISSUE TITLE
Not able to download anything

### ISSUE THREAD

**Issue by Momamari** [TEIC/romajs#135] opened 2022-01-28 00:25 UTC
Hey there! 
I am new to Roma, I don't know if I did something wrong, but whenever I try to download my scheme, I get this error message:

Roma is still in beta. The following error occurred:
TypeError: undefined is not an object (evaluating 'att.valList.valItem[Symbol.iterator]')

Would be thankful for any hint on how to deal with this issue.

**Comment by raffazizzi** [comment] 2022-01-28 00:34
Hello,

Thanks for reporting this. If you have uploaded an existing ODD, could you share it here so I can take a look? Or if you came across this problem after using Roma, do you know the steps to reproduce it? e.g. what customization did you start from and what changes did you make?

**Comment by Momamari** [comment] 2022-01-28 01:47
Hey,
I did not upload an existing ODD. I started with TEI Minimal, added the analysis module to the scheme, added a value to <s> and two values to <phr>. Additionally, I created a new element attribute for the <phr> tag and that's basically it.
Trying to download the scheme, I became the error message.
I reproduced it twice, but still wasn't able to download the ODD or the RelaxNG Schema.

**Comment by raffazizzi** [comment] 2022-01-28 01:50
Thanks, this is likely a bug. I will look into it

**Comment by JanelleJenstad** [comment] 2022-03-14 05:49
Hi @raffazizzi,
This is definitely a bug! I'm trying to use Roma Beta for my XML class at UVic. I'm getting this message:

Oh-oh... Something went wrong
Roma is still in beta. The following error occurred:

Uncaught SyntaxError: Failed to set the 'innerHTML' property on 'Element': The provided markup is

**Comment by raffazizzi** [comment] 2023-02-09 22:16
Hi all, I am still not able to replicate this issue. Can you let me know what browser are you using?
I tried with Chrome Version 109.0.5414.119  and Firefox 109.0.1

**Comment by raffazizzi** [comment] 2023-03-10 15:56
Closing because I can't reproduce this and haven't received follow up. Please re-open if this is still an issue for you.

**Closed by raffazizzi** 2023-03-10 15:56 UTC
Labels: awaiting response
