### ISSUE TITLE
Can't download ODD after creating attribute

### ISSUE THREAD

**Issue by martindholmes** [TEIC/romajs#18] opened 2018-09-10 04:21 UTC
After creating a new attribute (modifying tei_all), trying to download the ODD gets this error:

~~~~~
2bundle.js:69428 Uncaught TypeError: Cannot read property 'setAttribute' of null
    at _changeAttr (bundle.js:69428)
    at _loop7 (bundle.js:70001)
    at bundle.js:70028
    at _loop6 (bundle.js:70102)
    at updateElements (bundle.js:70128)
    at updateOdd (bundle.js:70170)
    at odd (bundle.js:67288)
    at combination (bundle.js:64684)
    at bundle.js:5462
    at dispatch (bundle.js:13512)
~~~~~

This is Chromium on Ubuntu 18.04.

**Comment by raffazizzi** [comment] 2018-09-10 05:14
This should be fixed now. Would you mind giving it another try? Make sure to do  hard refresh to get the latest JS

**Comment by martindholmes** [comment] 2018-09-10 06:50
Now I get this:

~~~~~
Uncaught TypeError: Cannot read property 'key' of null
    at _changeAttr (bundle.js:69602)
    at _loop7 (bundle.js:70007)
    at bundle.js:70036
    at _loop6 (bundle.js:70110)
    at updateElements (bundle.js:70136)
    at updateOdd (bundle.js:70178)
    at odd (bundle.js:67288)
    at combination (bundle.js:64684)
    at bundle.js:5462
    at dispatch (bundle.js:13512)
_changeAttr @ bundle.js:69602
_loop7 @ bundle.js:70007
(anonymous) @ bundle.js:70036
_loop6 @ bundle.js:70110
updateElements @ bundle.js:70136
updateOdd @ bundle.js:70178
odd @ bundle.js:67288
combination @ bundle.js:64684
(anonymous) @ bundle.js:5462
dispatch @ bundle.js:13512
(anonymous) @ bundle.js:65042
(anonymous) @ bundle.js:66621
downloadCustomization @ bundle.js:71381
onClick @ bundle.js:71474
callCallback @ bundle.js:48266
invokeGuardedCallbackDev @ bundle.js:48305
invokeGuardedCallback @ bundle.js:48162
invokeGuardedCallbackAndCatchFirstError @ bundle.js:48176
executeDispatch @ bundle.js:48560
executeDispatchesInOrder @ bundle.js:48582
executeDispatchesAndRelease @ bundle.js:48680
executeDispatchesAndReleaseTopLevel @ bundle.js:48691
forEachAccumulated @ bundle.js:48659
processEventQueue @ bundle.js:48836
runEventQueueInBatch @ bundle.js:51331
handleTopLevel @ bundle.js:51340
handleTopLevelImpl @ bundle.js:51071
batchedUpdates @ bundle.js:58806
batchedUpdates @ bundle.js:50054
dispatchEvent @ bundle.js:51145
~~~~~

**Comment by raffazizzi** [comment] 2018-09-10 07:02
Could you describe what steps you're taking?
E.g.
* edit ab
* add new attribute "foo'
* make required
* export ODD

(the above succeeds for me, while editing datatype restriction causes export to fail - I'm fixing that now).

**Comment by martindholmes** [comment] 2018-09-10 07:06
- edit ab
- add attribute "test"
- edit attribute "test"
- add closed valList with three values
- make required
- set datatype to teidata.name

export ODD

**Comment by raffazizzi** [comment] 2018-09-11 08:44
Couldn't reproduce with TEI All import. What ODD are you using? Thanks for helping!

**Comment by martindholmes** [comment] 2018-09-17 16:31
I was modifying tei_all.

**Closed** 2019-02-22 20:47 UTC
Labels: bug
