### ISSUE TITLE
request to edit attr ends up with blank page

### ISSUE THREAD

**Issue by sydb** [TEIC/romajs#168] opened 2024-07-11 21:41 UTC
Using Firefox 127.0.2 on Ubuntu when trying to edit an attribute I get a blank page. The source HTML is:
~~~html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Roma - ODD customization</title>
    <link href="[https://fonts.googleapis.com/css?family=Roboto:300,400,500](view-source:https://fonts.googleapis.com/css?family=Roboto:300,400,500)" rel="stylesheet">
    <link rel="stylesheet" href="[https://fonts.googleapis.com/icon?family=Material+Icons](view-source:https://fonts.googleapis.com/icon?family=Material+Icons)">
    <link rel="shortcut icon" href="[favicon.ico](view-source:https://roma.tei-c.org/element/abstract/favicon.ico)" type="image/png/ico" />
    <link rel="icon" href="[favicon.ico](view-source:https://roma.tei-c.org/element/abstract/favicon.ico)" sizes="32x32" />
    <link rel="icon" href="[favicon.ico](view-source:https://roma.tei-c.org/element/abstract/favicon.ico)" sizes="192x192" />
    <link rel="apple-touch-icon" href="[favicon.ico](view-source:https://roma.tei-c.org/element/abstract/favicon.ico)" />
    <link rel="shortcut icon" href="[favicon.ico](view-source:https://roma.tei-c.org/element/abstract/favicon.ico)" type="image/png/ico" />
    <meta name="msapplication-TileImage" content="favicon.ico" />
  <link rel="shortcut icon" href="[favicon.ico](view-source:https://roma.tei-c.org/element/abstract/favicon.ico)"></head>
  <body>
    <div id="romajs" data-basename=""></div>
  <script type="text/javascript" src="[romajs_313cc6364b0b568ea889.js](view-source:https://roma.tei-c.org/element/abstract/romajs_313cc6364b0b568ea889.js)"></script></body>
</html>
~~~
I then tried to edit the Javascript program by opening `https://roma.tei-c.org/element/abstract/romajs_313cc6364b0b568ea889.js` (I tried to open it both by using `wget` and by opening in oXygen). What is returned is HTML, not Javascript, and is byte-for-byte the same as the HTML above.

This problem noticed by Gabriel Calarco and first reported to TEI-L 2024-07-11 21:28Z.

**Comment by sydb** [comment] 2024-07-12 00:50
May be a duplicate of #167 …

**Comment by raffazizzi** [comment] 2024-07-12 00:54
Duplicate of #167.

**Closed by raffazizzi** 2024-07-12 00:54 UTC
Labels: bug
